export const CONTENT = {
es: {
t: {
hello: "Hola, soy Lucía.",
invite: "Soy Program Manager Lead. En vez de contarte mi currículum, te invito a pasar un día conmigo: dos minutos, y tú decides qué mirar.",
who: "Antes de empezar, ¿quién eres?",
restart: "Empezar de nuevo", dayLabel: "Horas del día",
prev: "Atrás", next: "Siguiente hora", mail: "Escríbeme",
flashOpen: "Flashback: ¿de dónde viene esto?", flashClose: "Cerrar flashback"
},
introBubble: "¿Pasas el día conmigo?",
personas: [
{ id: "r", title: "Soy recruiter", text: "Tengo poco tiempo: dame los datos." },
{ id: "c", title: "Trabajo en operaciones o educación", text: "Quiero ver cómo lo haces." },
{ id: "q", title: "Solo tengo curiosidad", text: "Cuéntame tu historia." }
],
forYou: { r: "El dato:", c: "El cómo:", q: "Sobre mí:" },
ch: [
{ title: "Jugo de naranja y Slack", bubble: "Primero jugo de naranja. Después, Slack.",
body: "Lo primero es contestar los mensajes de Slack, por si hay algo urgente que necesite mi atención. Después reviso las tareas que tengo pautadas para el día, sabiendo que casi siempre aparecen otras por el camino.",
extra: { r: "coordino los programas de AI Engineering y AI Engineering for Devs en España y Latinoamérica, en remoto.", c: "primero lo urgente, después lo planificado. Kanban con Notion, Asana y Trello.", q: "vivo en Valencia y empecé mi carrera en Montevideo." },
flashWhen: "2008 · Montevideo",
flash: "Empecé en Casa de Galicia atendiendo al público y despachando citas médicas. Ahí aprendí a distinguir lo urgente de lo importante, que es justo lo que hago cada mañana al abrir Slack." },
{ title: "Algo se tuerce", bubble: "Respira. Para esto hay un plan.",
body: "Una cohorte empieza en cinco días y el mentor todavía no ha confirmado.",
question: "¿Qué harías tú?",
options: ["Escribirle al mentor y esperar", "Buscar un sustituto ya mismo", "Revisar el checklist y activar el plan B en paralelo"],
feedback: ["Funciona si responde. Mientras tanto, el riesgo es tuyo.", "Rápido, pero quizá innecesario: aún no sabes qué pasa.", "Esa es la mía."],
reveal: "Y casi nunca llego a este punto: mis automatizaciones revisan las cohortes próximas y me avisan de lo que falta antes de que sea urgente.",
extra: { r: "diseñé automatizaciones de punta a punta para cambios de estado e incidencias.", c: "n8n, Make, Zapier y GitHub Actions, y cada vez más agentes de IA y skills.", q: "prefiero que los problemas me encuentren preparada." },
flashWhen: "2018 · Casa de Galicia",
flash: "Llevando la comunicación digital me tocó gestionar una crisis de imagen en redes. Desde entonces prefiero tener el plan antes que la crisis." },
{ title: "Hora de construir", bubble: "Si se repite, lo automatizo.",
body: "Este rato es para construir. Automatizo lo que se repite, como la creación de cohortes, y trabajé junto a un compañero en el desarrollo de una plataforma interna para que los mentores gestionen a sus alumnos.",
question: "¿Qué automatizarías primero?",
options: ["La creación de cohortes y sus cambios de estado", "El seguimiento de los estudiantes", "El seguimiento de graduados que buscan empleo"],
feedback: ["Buena elección.", "Buena elección.", "Buena elección."],
reveal: "Yo automaticé las tres. La última ni siquiera era de mi área: la construí para el departamento de Carreras.",
extra: { r: "además de Program Manager, soy desarrolladora.", c: "automatizaciones sin código cuando alcanza, código propio cuando hace falta.", q: "cuando la herramienta no existe, la armo." },
flashWhen: "2022 · Bootcamp",
flash: "Me formé como Full Stack Software Developer en 4Geeks Academy. Por eso hoy puedo construir yo misma lo que el equipo necesita, en vez de solo pedirlo." },
{ title: "Una hora para aprender", bubble: "Hoy toca: agentes de IA.",
body: "Me reservo tiempo para formarme: desarrollo con IA, agentes, skills y las tendencias que van saliendo. Lo que aprendo termina convertido en mejoras para el equipo.",
extra: { r: "en 2025 completé la formación de preparación para PMP y SMPC (EIGP).", c: "ahora mismo, agentes de IA y skills aplicados a la operación diaria.", q: "aprender mientras trabajo es mi estado natural." },
flashWhen: "2013–2018 · Universidad Católica del Uruguay",
flash: "Estudié Comunicación Social mientras trabajaba a tiempo completo. Formarme en paralelo al trabajo es un hábito que mantengo desde entonces." },
{ title: "Sync con el equipo", bubble: "Lunes, 16:00: sync.",
body: "Los lunes a las 16:00 hacemos sync con mi equipo, y los viernes nos reunimos todos los Program Managers de España, Latinoamérica y Estados Unidos. Con ese ritmo y un modelo de seguimiento estructurado subimos las valoraciones de los alumnos y la tasa de graduación.",
extra: { r: "coordino un equipo de hasta 5 personas y hemos supervisado hasta 500 estudiantes activos en paralelo en múltiples programas.", c: "lideré la unificación operativa entre España y Latinoamérica: mismos procesos y flujos para todos.", q: "llegué a coordinar también cohortes en Europa." },
flashWhen: "2020 · Casa de Galicia",
flash: "Lideré a más de 20 personas y fui el enlace entre departamentos, equipo técnico y dirección. Esa experiencia gestionando equipos y departamentos es la razón por la que, un año después del bootcamp, 4Geeks me confió la coordinación de sus programas." },
{ title: "Fin del día", bubble: "¿Hablamos mañana?",
body: "Este es uno de mis días; otros traen cosas distintas. Si necesitas a alguien que coordine programas, ordene procesos y además construya las herramientas, hablemos.",
extra: { r: "Program Manager Lead y desarrolladora, inglés C1, Valencia.", c: "me encanta comparar procesos: escríbeme y cuéntame el tuyo.", q: "gracias por quedarte hasta el final." } },
{ title: "Después del trabajo", bubble: "Ahora, lo mío.",
body: "Cuando cierro el portátil me pongo a crear con las manos. Tengo muchos hobbies que voy alternando; el último ha sido la sublimación.",
extra: { r: "aprender cosas nuevas es lo que más me gusta, dentro y fuera del trabajo.", c: "no le tengo miedo a los desafíos: si no sé hacerlo, aprendo.", q: "me encantan las manualidades y crear con mis manos." } }
]
},
en: {
t: {
hello: "Hi, I'm Lucía.",
invite: "I'm a Program Manager Lead. Instead of walking you through my résumé, spend a day with me: two minutes, and you choose what to look at.",
who: "Before we start, who are you?",
restart: "Start over", dayLabel: "Hours of the day",
prev: "Back", next: "Next hour", mail: "Email me",
flashOpen: "Flashback: where does this come from?", flashClose: "Close flashback"
},
introBubble: "Spend the day with me?",
personas: [
{ id: "r", title: "I'm a recruiter", text: "I'm short on time: give me the facts." },
{ id: "c", title: "I work in operations or education", text: "Show me how you do it." },
{ id: "q", title: "I'm just curious", text: "Tell me your story." }
],
forYou: { r: "The fact:", c: "The how:", q: "About me:" },
ch: [
{ title: "Orange juice and Slack", bubble: "Orange juice first. Then Slack.",
body: "First I answer my Slack messages, in case something urgent needs my attention. Then I go through the tasks planned for the day, knowing that others almost always show up along the way.",
extra: { r: "I coordinate the AI Engineering and AI Engineering for Devs programs in Spain and Latin America, remotely.", c: "urgent first, planned second. Kanban with Notion, Asana and Trello.", q: "I live in Valencia and started my career in Montevideo." },
flashWhen: "2008 · Montevideo",
flash: "I started at Casa de Galicia in customer service, booking medical appointments. That's where I learned to tell urgent from important, which is exactly what I do every morning when I open Slack." },
{ title: "Something goes sideways", bubble: "Breathe. There's a plan for this.",
body: "A cohort starts in five days and the mentor still hasn't confirmed.",
question: "What would you do?",
options: ["Message the mentor and wait", "Find a substitute right now", "Check the checklist and start plan B in parallel"],
feedback: ["It works if they reply. Until then, the risk is yours.", "Fast, but maybe unnecessary: you don't know what's going on yet.", "That's my pick."],
reveal: "And I rarely get this far: my automations check upcoming cohorts and flag what's missing before it becomes urgent.",
extra: { r: "I designed end-to-end automations for status changes and incidents.", c: "n8n, Make, Zapier and GitHub Actions, and increasingly AI agents and skills.", q: "I like problems to find me prepared." },
flashWhen: "2018 · Casa de Galicia",
flash: "Running digital communication, I had to handle a reputation crisis on social media. Since then I prefer having the plan before the crisis." },
{ title: "Time to build", bubble: "If it repeats, I automate it.",
body: "This slot is for building. I automate what repeats, like cohort creation, and I worked with a teammate on building an internal platform mentors use to manage their students.",
question: "What would you automate first?",
options: ["Cohort creation and status changes", "Student follow-up", "Follow-up of graduates looking for a job"],
feedback: ["Good choice.", "Good choice.", "Good choice."],
reveal: "I automated all three. The last one wasn't even my area: I built it for the Careers department.",
extra: { r: "besides being a Program Manager, I'm a developer.", c: "no-code automation when it's enough, my own code when it isn't.", q: "when the tool doesn't exist, I build it." },
flashWhen: "2022 · Bootcamp",
flash: "I trained as a Full Stack Software Developer at 4Geeks Academy. That's why today I can build what the team needs myself, instead of just asking for it." },
{ title: "An hour to learn", bubble: "Today: AI agents.",
body: "I set time aside to keep learning: AI-assisted development, agents, skills and whatever is emerging. What I learn ends up as improvements for the team.",
extra: { r: "in 2025 I completed PMP and SMPC preparation training (EIGP).", c: "right now, AI agents and skills applied to daily operations.", q: "learning while working is my natural state." },
flashWhen: "2013–2018 · Universidad Católica del Uruguay",
flash: "I studied Social Communication while working full time. Learning alongside the job is a habit I've kept ever since." },
{ title: "Team sync", bubble: "Monday, 4 pm: sync.",
body: "On Mondays at 4 pm I sync with my team, and on Fridays all the Program Managers from Spain, Latin America and the United States meet. With that rhythm and a structured follow-up model, we raised student ratings and the graduation rate.",
extra: { r: "I coordinate a team of up to 5, and we have overseen up to 500 active students in parallel across multiple programs.", c: "I led the operational unification between Spain and Latin America: the same processes and workflows for everyone.", q: "I've also coordinated cohorts in Europe." },
flashWhen: "2020 · Casa de Galicia",
flash: "I led 20+ people and was the link between departments, the tech team and leadership. That experience managing teams and departments is why, a year after the bootcamp, 4Geeks trusted me with coordinating its programs." },
{ title: "End of the day", bubble: "Talk tomorrow?",
body: "This is one of my days; others bring different things. If you need someone who coordinates programs, brings order to processes and also builds the tools, let's talk.",
extra: { r: "Program Manager Lead and developer, C1 English, Valencia.", c: "I love comparing processes: write to me and tell me about yours.", q: "thanks for staying until the end." } },
{ title: "After work", bubble: "Now, my own things.",
body: "When I close the laptop I start making things with my hands. I have lots of hobbies that I rotate; the latest has been sublimation printing.",
extra: { r: "learning new things is what I enjoy most, in and out of work.", c: "I'm not afraid of challenges: if I don't know how, I learn.", q: "I love crafts and making things with my hands." } }
]
}
};

